name: docker-publish

on:
  release:
    types: [published]
  schedule:
    - cron: '0 4 * * 3'
  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      -
        name: Build and push master
        uses: docker/build-push-action@v2
        with:
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          push: true
          buildArgs: build_branch=master
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/mmbtools:master,
                ${{ secrets.DOCKER_HUB_USERNAME }}/mmbtools:latest
      -
        name: Build and push next
        uses: docker/build-push-action@v2
        with:
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          push: true
          build-args: build_branch=next
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/mmbtools:next
